function CSM_export_AllStresses(dim, Stresses, vertices, elements, outputFileName, iter, variableName)
%CSM_EXPORT_VONMISESSTRESS export a (P1) Cell-Based stress tensor to vtk (binary) file

%   This file is part of redbKIT.
%   Author: Luca Rosafalco <luca.rosafalco at polimi.it> 

titleData = 'CSM_AllStresses';
if nargin < 6
      iter = -1;
end

if dim == 2
      
      if nargin < 7
          %ATTENZIONE: da controllare
          variableName = {'sigmax', 'sigmay', 'sigmaz', 'sigmaxy'};
      end
     
      exportData = struct('iteration', {iter},...
            'vertices', {vertices'},...
            'elements', {elements(1:3,:)'},...
            'outputFile', {outputFileName},...
            'title', {titleData},...
            'variableName',{{'sigmax', 'sigmay', 'sigmaz', 'sigmaxy'}},...
            'variableType',{{'SCALARS','SCALARS','SCALARS','SCALARS'}},...
            'variableData',{{Stresses(:,1)',...
                             Stresses(:,2)',...
                             Stresses(:,3)',...
                             Stresses(:,4)'}});
      
      exporter2dVTK_cell(exportData);
      
elseif dim == 3
      
     if nargin < 7
         %ATTENZIONE: da controllare
         variableName = ['sigmax','sigmay','sigmaz','sigmaxy','sigmaxz','sigmayz'];
     end
    
      exportData=struct('iteration', {iter},...
            'vertices', {vertices'},...
            'elements', {elements(1:4,:)'},...
            'outputFile', {outputFileName},...
            'title', {titleData},...
            'variableName',{{variableName}},...
            'variableType',{{'SCALARS'}},...
            'variableData',{{Stresses(:,1)',...
                             Stresses(:,2)',...
                             Stresses(:,3)',...
                             Stresses(:,4)',...
                             Stresses(:,5)',...
                             Stresses(:,6)'}});
        
      exporter3dVTK_cell(exportData);
end
